Repository apecloud/kubeblocks-addons, pull requests merged in 2025-05, with the labels that each got.

#1652 chore: fix etcd cluster svc
  addons-cluster/etcd/templates/_helpers.tpl
  addons-cluster/etcd/values.schema.json
  addons-cluster/etcd/values.yaml
Labels: pick-1.0-beta

#1654 chore: use vars defined in cmpd to replace KB_ envs
  addons/mongodb/dataprotection/mongo-pitr-restore.sh
  addons/postgresql/dataprotection/wal-g-backup.sh
  addons/postgresql/dataprotection/wal-g-incremental-backup.sh
  addons/postgresql/templates/cmpd-12.yaml
  addons/postgresql/templates/cmpd-14.yaml
  addons/postgresql/templates/cmpd-15.yaml
  addons/postgresql/templates/cmpd-16.yaml
Labels: pick-1.0-beta

#1649 feat: support neo4j
  .github/CODEOWNERS
  README.md
  addons-cluster/neo4j/.helmignore
  addons-cluster/neo4j/Chart.yaml
  addons-cluster/neo4j/templates/NOTES.txt
  addons-cluster/neo4j/templates/_helpers.tpl
  addons-cluster/neo4j/templates/cluster.yaml
  addons-cluster/neo4j/templates/validate.yaml
  addons-cluster/neo4j/values.schema.json
  addons-cluster/neo4j/values.yaml
  addons/neo4j/.helmignore
  addons/neo4j/Chart.yaml
  addons/neo4j/README.md
  addons/neo4j/config/neo4j-config.tpl
  addons/neo4j/templates/NOTES.txt
  addons/neo4j/templates/_helpers.tpl
  addons/neo4j/templates/_names.tpl
  addons/neo4j/templates/clusterdefinition.yaml
  addons/neo4j/templates/cmpd.yaml
  addons/neo4j/templates/cmpv.yaml
  addons/neo4j/templates/config-template.yaml
  addons/neo4j/values.yaml
Labels: pick-1.0-beta

#1661 chore: fix shellspec test error
  .github/CODEOWNERS
  addons/redis/scripts-ut-spec/redis_cluster_replica_member_leave_spec.sh
Labels: pick-1.0-beta, pick-1.0

#1657 fix: rabbitmq leave member failed
  addons/rabbitmq/scripts/member_leave.sh
Labels: pick-1.0

#1665 chore: change addon maintainers name
  .github/CODEOWNERS
  README.md
  addons-cluster/etcd/Chart.yaml
  addons/etcd/Chart.yaml
  addons/llm/Chart.yaml
  addons/neon/Chart.yaml
  addons/orchestrator/Chart.yaml
  addons/redis/Chart.yaml
  addons/xinference/Chart.yaml
  addons/zookeeper/Chart.yaml
  hack/update-codeowners.sh
Labels: pick-1.0

#1664 chore: upgrade tidb-6 to 6.5.12
  README.md
  addons/tidb/templates/cmpv.yaml
Labels: pick-1.0

#1663 chore: kfk2's config template should be helm resource policy keep
  addons/kafka/templates/config-template.yaml
Labels: pick-1.0

#1660 feat: kfk's jmx-exporter support hot reload
  .github/CODEOWNERS
  README.md
  addons/kafka/templates/cmpd-broker-27.yaml
  addons/kafka/templates/cmpd-broker.yaml
  addons/kafka/templates/cmpd-combine.yaml
  addons/kafka/templates/cmpd-controller.yaml
Labels: pick-1.0

#1668 chore: install yq
  .github/CODEOWNERS
  .github/workflows/check-chart-push.yml
  README.md
Labels: pick-1.0

#1671 chore: move mysql tmpdir to data volume to prevent consuming space on the root filesystem
  addons/mysql/config/mysql5.7-config.tpl
  addons/mysql/config/mysql8.0-config.tpl
  addons/mysql/templates/_helpers.tpl
Labels: pick-1.0

#1673 fix: upgrade syncer for vanpg timeline mismatch
  addons/vanilla-postgresql/values.yaml
Labels: pick-1.0

#1658 chore: remove mysql/pdb-x dashboard cm
  addons/mysql/templates/configmap-dashboards.yaml
  addons/polardbx/templates/configmap-dashboards.yaml
Labels: pick-1.0

#1676 chore: add neo4j to helm repo
  .github/workflows/release-addons-cluster-chart.yml
  .github/workflows/release-chart.yml
Labels: enhancement, pick-1.0

#1678 fix: orc switchover action
  addons/mysql/templates/_orc.tpl
  addons/mysql/templates/cmpd-mysql57-orc.yaml
  addons/mysql/templates/cmpd-mysql80-orc.yaml
  addons/mysql/templates/switchover.yaml
Labels: pick-1.0

#1670 fix: etcd restore
  addons/etcd/config/etcd.conf.yaml.tpl
  addons/etcd/dataprotection/backup.sh
  addons/etcd/dataprotection/prepare-for-restore.sh
  addons/etcd/dataprotection/restore.sh
  addons/etcd/scripts-ut-spec/common_spec.sh
  addons/etcd/scripts-ut-spec/start_spec.sh
  addons/etcd/scripts/common.sh
  addons/etcd/scripts/start.sh
  addons/etcd/templates/backupactionset.yaml
  addons/etcd/templates/backuppolicytemplate.yaml
  addons/etcd/templates/cmpd.yaml
  addons/etcd/values.yaml
Labels: pick-1.0

#1680 fix: redis sentinel scale in failed
  addons/redis/scripts/redis-sentinel-member-leave.sh
  addons/redis/templates/cmpd-redis-7.yaml
Labels: pick-1.0

#1682 fix: remove neo4j versions like 2025.xx.xx
  README.md
  addons-cluster/neo4j/values.schema.json
  addons/neo4j/templates/cmpv.yaml
Labels: pick-1.0

#1681 chore: set redis podManagementPolicy to OrderedReady
  addons/redis/templates/cmpd-redis-7.yaml
  addons/redis/templates/cmpd-redis-cluster-7.yaml
Labels: pick-1.0

#1686 chore: fix shellspec test error
  addons/redis/scripts-ut-spec/redis_sentinel_member_leave_spec.sh
Labels: pick-1.0

#1679 chore: set pg max_worker_processes to 8
  addons/orioledb/config/pg16-config.tpl
  addons/postgresql/config/pg12-config.tpl
  addons/postgresql/config/pg14-config.tpl
  addons/postgresql/config/pg15-config.tpl
  addons/postgresql/config/pg16-config.tpl
  addons/vanilla-postgresql/config/pg12-config.tpl
  addons/vanilla-postgresql/config/pg14-config.tpl
  addons/vanilla-postgresql/config/pg15-config.tpl
Labels: pick-1.0

#1687 fix: create orioledb failed
  addons/orioledb/config/pg16-config.tpl
  addons/orioledb/templates/cmpd.yaml
  addons/orioledb/templates/paramsdef.yaml
  addons/orioledb/templates/pcr.yaml
Labels: pick-1.0

#1672 fix: delete member if possible before pd joining a cluster
  addons/tidb/scripts-ut-spec/pd_start_spec.sh
  addons/tidb/scripts/pd_start.sh
Labels: pick-1.0

#1690 chore: support to scale out shards for clickhouse
  addons/clickhouse/scripts/member-join.sh
  addons/clickhouse/scripts/post-for-rebuild.sh
  addons/clickhouse/scripts/post-for-scale-out-shard.sh
  addons/clickhouse/templates/opsdefinition.yaml
Labels: pick-1.0

#1692 fix:mysql tmp dir error
  addons/mysql/config/mysql5.7-config.tpl
  addons/mysql/config/mysql8.0-config.tpl
  addons/mysql/templates/_helpers.tpl
  addons/mysql/templates/cmpd-mysql57-orc.yaml
  addons/mysql/templates/cmpd-mysql80-orc.yaml
Labels: pick-1.0

#1693 chore: improve zookeeper tracelog
  addons/zookeeper/config/log4j.properties
Labels: pick-0.9, pick-1.0

#1695 fix: pg addon only partial apply config changes
  addons/postgresql/scripts/postgres-setup.sh
Labels: pick-1.0

#1696 Revert "chore: set pg max_worker_processes to 8"
  addons/orioledb/config/pg16-config.tpl
  addons/postgresql/config/pg12-config.tpl
  addons/postgresql/config/pg14-config.tpl
  addons/postgresql/config/pg15-config.tpl
  addons/postgresql/config/pg16-config.tpl
  addons/vanilla-postgresql/config/pg12-config.tpl
  addons/vanilla-postgresql/config/pg14-config.tpl
  addons/vanilla-postgresql/config/pg15-config.tpl
Labels: pick-1.0

#1698 fix: redis cluster restore failed
  addons/redis/dataprotection/backup.sh
Labels: pick-1.0

#1700 chore: fix shell spec test
  addons/postgresql/scripts-ut-spec/postgres_setup_spec.sh
Labels: pick-1.0
