Repository apecloud/kubeblocks-addons, pull requests merged in 2025-09, with the labels that each got.

#1943 fix: tidb minor problems
  addons/tidb/config/tidb.toml.tpl
  addons/tidb/scripts/pd_memberleave.sh
  addons/tidb/scripts/tidb_postprovision.sh
  addons/tidb/scripts/tikv_member_leave.sh
  addons/tidb/templates/cmpd-pd.yaml
Labels: pick-1.0

#1961 chore: replace bitnami repository with apecloud
  addons/influxdb/values.yaml
  addons/milvus/values.yaml
  addons/mysql/values.yaml
  addons/solr/values.yaml
  addons/zookeeper/values.yaml
Labels: nopick

#1949 chore: pg remove config-wal-g action set
  addons/postgresql/README.md
  addons/postgresql/dataprotection/wal-g-archive-restore.sh
  addons/postgresql/dataprotection/wal-g-archive.sh
  addons/postgresql/dataprotection/wal-g-backup.sh
  addons/postgresql/dataprotection/wal-g-config-restore.sh
  addons/postgresql/dataprotection/wal-g-config.sh
  addons/postgresql/dataprotection/wal-g-incremental-backup.sh
  addons/postgresql/dataprotection/wal-g-restore.sh
  addons/postgresql/templates/actionset-wal-g-pitr.yaml
  addons/postgresql/templates/actionset-wal-g.yaml
  addons/postgresql/templates/backuppolicytemplate.yaml
  addons/postgresql/values.yaml
  examples/postgresql/README.md
  examples/postgresql/backup-pg-basebasekup.yaml
  examples/postgresql/backup-wal-g.yaml
  examples/postgresql/config-wal-g.yaml
Labels: pick-1.0

#1933 chore: make qdrant cmpd mutable
  addons/qdrant/templates/cmpd.yaml
Labels: pick-1.0

#1952 fix[elasticsearch]: backup and restore failed
  addons/elasticsearch/agent/main.go
  addons/elasticsearch/templates/cmpd-es-7.yaml
  addons/elasticsearch/templates/cmpd-es-8.yaml
  addons/elasticsearch/templates/cmpv-es.yaml
Labels: pick-1.0

#1955 chore: update kafka zk example
  addons/kafka/README.md
  examples/kafka/README.md
  examples/kafka/cluster-2x-ext-zk-svc-descriptor.yaml
Labels: pick-1.0

#1968 chore: support redis 8.2
  README.md
  addons/redis/values.yaml
Labels: pick-0.9, pick-1.0

#1969 fix: pg wal-g archive without time range
  addons/postgresql/dataprotection/common-scripts.sh
  addons/postgresql/dataprotection/wal-g-archive.sh
  addons/postgresql/scripts/postgres-pre-setup.sh
  addons/postgresql/templates/_helpers.tpl
  addons/postgresql/templates/actionset-wal-g-incremental.yaml
  addons/postgresql/templates/actionset-wal-g-pitr.yaml
  addons/postgresql/templates/actionset-wal-g.yaml
  addons/postgresql/templates/cmpv.yaml
  addons/postgresql/values.yaml
Labels: pick-1.0

#1973 fix: reconfigure on Redis cluster doesn't work for client-output-buffer-limit
  addons/redis/config/redis-cluster7-config-constraint.cue
Labels: pick-1.0

#1974 fix: switchover failed when replicas is 1
  addons/clickhouse/scripts/keeper-switchover.sh
  addons/clickhouse/templates/cmpd-keeper.yaml
  addons/etcd/scripts/switchover.sh
  addons/etcd/templates/cmpd.yaml
Labels: pick-1.0

#1977 fix: keeper switch over failed
  addons/clickhouse/scripts/keeper-member-join.sh
  addons/clickhouse/scripts/keeper-member-leave.sh
  addons/clickhouse/scripts/keeper-switchover.sh
Labels: pick-1.0

#1978 chore: remove keeper duplicate check
  addons/clickhouse/scripts/keeper-switchover.sh
Labels: pick-1.0

#1984 chore: skip check the role after switch without candicate
  addons/etcd/scripts/switchover.sh
  addons/redis/redis-cluster-scripts/redis-cluster-switchover.sh
  addons/redis/scripts/redis-switchover.sh
Labels: pick-1.0

#1989 fix: mongodb restore failed
  addons/mongodb/dataprotection/common-scripts.sh
  addons/mongodb/dataprotection/shard-pbm-restore-prepare.sh
  addons/mongodb/scripts-ut-spec/replicaset_setup_spec.sh
  addons/mongodb/scripts/replicaset-setup.tpl
Labels: pick-1.0

#1996 chore: mongodb restore failed
  addons/mongodb/dataprotection/common-scripts.sh
  addons/mongodb/dataprotection/shard-pbm-restore-prepare.sh
  addons/mongodb/scripts/replicaset-setup.tpl
  addons/mongodb/templates/componentdefinition.yaml
Labels: nopick

#2000 fix: redis cluster start failed
  addons/redis/redis-cluster-scripts/redis-cluster-server-start.sh
  addons/redis/redis-cluster-scripts/redis-cluster5-server-start.sh
  addons/redis/redis-cluster-scripts/redis-cluster6-server-start.sh
Labels: pick-1.0

#2017 chore: pg only audit ddl
  addons/postgresql/config/pg12-config.tpl
  addons/postgresql/config/pg14-config.tpl
  addons/postgresql/config/pg15-config.tpl
  addons/postgresql/config/pg16-config.tpl
  addons/postgresql/config/pg17-config.tpl
Labels: pick-0.9, pick-1.0

#2018 chore: add remote service descriptor for pg standy instance
  addons-cluster/postgresql/templates/_helpers.tpl
  addons-cluster/postgresql/templates/remote-service-descriptor.yaml
  addons-cluster/postgresql/values.yaml
Labels: pick-1.0

#2023 chore: fix pg opsdef that use unknown env
  addons/postgresql/scripts/reload_patroni_config.sh
  addons/postgresql/templates/update_standby_config.yaml
Labels: pick-1.0

#2006 fix: ck & etcd dashboards
  addons/clickhouse/dashboards/clickhouse.json
  addons/clickhouse/templates/_helpers.tpl
  addons/clickhouse/templates/actionset-incremental.yaml
  addons/clickhouse/templates/actionset.yaml
  addons/clickhouse/values.yaml
  addons/etcd/dashboards/etcd.json
Labels: pick-0.9, pick-1.0

#2024 feat: Add support etcd podAntiAffinity
  addons-cluster/etcd/templates/_helpers.tpl
  addons-cluster/etcd/templates/cluster.yaml
  addons-cluster/etcd/values.yaml
Labels: pick-1.0

#2029 chore: add release-chart-image for kubeblocks-addons
  .github/workflows/release-chart-image.yml
Labels: pick-0.9, pick-1.0

#2030 fix[elasticsearch]: upgrade failed
  addons/elasticsearch/templates/_helpers.tpl
Labels: pick-1.0

#2037 feat[qdrant]: support new version v1.15.4
  README.md
  addons/qdrant/Chart.yaml
  addons/qdrant/values.yaml
Labels: pick-1.0

#2046 fix: set pvc for loki-write
  .gitignore
  addons-cluster/loki/templates/cluster.yaml
  addons-cluster/loki/values.yaml
Labels: pick-1.0

#2049 chore: remove addon tutorial links
  hack/readme-header.tpl
Labels: pick-1.0

#2050 chore: update mongodb exporter args
  addons/mongodb/templates/cmpd.yaml
Labels: pick-0.9, pick-1.0

#2051 fix: mysql parameter effect scope
  addons/mysql/config/mysql5.7-config-constraint.cue
  addons/mysql/config/mysql5.7-config-effect-scope.yaml
  addons/mysql/config/mysql8-config-constraint.cue
  addons/mysql/config/mysql8-config-effect-scope.yaml
Labels: pick-1.0

#2056 chore: upgrade mysql addon version to 1.0.3
  addons/mysql/Chart.yaml
Labels: nopick

#2062 fix: remove huge max constraint of parameters
  addons/postgresql/config/pg12-config-constraint.cue
  addons/postgresql/config/pg14-config-constraint.cue
  addons/postgresql/config/pg15-config-constraint.cue
  addons/postgresql/config/pg16-config-constraint.cue
  addons/postgresql/config/pg17-config-constraint.cue
Labels: pick-0.9, pick-1.0

#2066 chore: rename rabbitmq vars
  addons/rabbitmq/config/erlang.cookie.tpl
  addons/rabbitmq/config/rabbitmq-config.tpl
  addons/rabbitmq/templates/cmpd.yaml
Labels: pick-1.0

#2074 fix[elasticsearch]: addon upgrade failed
  addons/elasticsearch/templates/_helpers.tpl
  addons/elasticsearch/templates/cmpd-es-6.yaml
Labels: pick-1.0

#2075 chore: add update-release-notes workflow
  .github/workflows/update-release-notes.yml
Labels: pick-0.9, pick-1.0

#2077 chore: missing some parameters def
  addons/redis/config/redis-cluster7-config-constraint.cue
Labels: pick-1.0

#2071 fix[elasticsearch]: 6.x and 7.x backup failed
  addons/elasticsearch/Chart.yaml
  addons/elasticsearch/dataprotection/backup.sh
  addons/elasticsearch/plugins/Dockerfile
  addons/elasticsearch/scripts/install-plugins.sh
  addons/elasticsearch/templates/cmpd-es-6.yaml
  addons/elasticsearch/templates/cmpd-es-7.yaml
  addons/elasticsearch/templates/cmpd-es-8.yaml
  addons/elasticsearch/templates/cmpd-es-data-6.yaml
  addons/elasticsearch/templates/cmpd-es-data-7.yaml
  addons/elasticsearch/templates/cmpd-es-data-8.yaml
  addons/elasticsearch/templates/cmpd-es-master-6.yaml
  addons/elasticsearch/templates/cmpd-es-master-7.yaml
  addons/elasticsearch/templates/cmpd-es-master-8.yaml
  addons/elasticsearch/templates/cmpv-es.yaml
  addons/elasticsearch/values.yaml
Labels: pick-1.0

#2082 chore: mysql support to set architecture
  addons/mysql/templates/_helpers.tpl
  addons/mysql/values.yaml
Labels: pick-1.0
