Repository apecloud/kubeblocks-addons, pull requests merged in 2025-06, with the labels that each got.

#1703 chore: pcr support multi version
  addons/apecloud-mysql/templates/_names.tpl
  addons/apecloud-mysql/templates/pcr-wescale.yaml
  addons/apecloud-mysql/templates/pcr-wesql.yaml
  addons/mysql/templates/_names.tpl
  addons/mysql/templates/pcr-57-orc.yaml
  addons/mysql/templates/pcr-57.yaml
  addons/mysql/templates/pcr-80-mgr.yaml
  addons/mysql/templates/pcr-80-orc.yaml
  addons/mysql/templates/pcr-80.yaml
  addons/mysql/templates/pcr-84-mgr.yaml
  addons/mysql/templates/pcr-84.yaml
  addons/oceanbase-ce/templates/_helpers.tpl
  addons/oceanbase-ce/templates/pcr.yaml
  addons/orioledb/templates/pcr.yaml
  addons/postgresql/templates/_helpers.tpl
  addons/postgresql/templates/pcr-12.yaml
  addons/postgresql/templates/pcr-14.yaml
  addons/postgresql/templates/pcr-15.yaml
  addons/postgresql/templates/pcr-16.yaml
  addons/pulsar/templates/_helpers.tpl
  addons/pulsar/templates/config/pcr-bkrecovery-2.yaml
  addons/pulsar/templates/config/pcr-bkrecovery-3.yaml
  addons/pulsar/templates/config/pcr-bookies-2.yaml
  addons/pulsar/templates/config/pcr-bookies-3.yaml
  addons/pulsar/templates/config/pcr-broker-2.yaml
  addons/pulsar/templates/config/pcr-broker-3.yaml
  addons/pulsar/templates/config/pcr-proxy-2.yaml
  addons/pulsar/templates/config/pcr-proxy-3.yaml
  addons/pulsar/templates/config/pcr-zookeeper-2.yaml
  addons/pulsar/templates/config/pcr-zookeeper-3.yaml
  addons/redis/templates/_helpers.tpl
  addons/redis/templates/pcr-redis-cluster.yaml
  addons/redis/templates/pcr-redis.yaml
  addons/tidb/templates/_helpers.tpl
  addons/tidb/templates/pcr-pd.yaml
  addons/tidb/templates/pcr-tidb.yaml
  addons/tidb/templates/pcr-tikv.yaml
  addons/vanilla-postgresql/templates/_helpers.tpl
  addons/vanilla-postgresql/templates/pcr-12.yaml
  addons/vanilla-postgresql/templates/pcr-14.yaml
  addons/vanilla-postgresql/templates/pcr-15-supabase.yaml
  addons/vanilla-postgresql/templates/pcr-15.yaml
Labels: pick-1.0

#1715 fix: ck restore rbac
  addons/clickhouse/configs/00_default_overrides.xml.tpl
  addons/clickhouse/configs/clickhouse-config-constraint.cue
  addons/clickhouse/configs/clickhouse-user-constraint.cue
  addons/clickhouse/configs/user.xml.tpl
  addons/clickhouse/dataprotection/backup.sh
  addons/clickhouse/dataprotection/common.sh
  addons/clickhouse/dataprotection/incremental-backup.sh
  addons/clickhouse/dataprotection/incremental-restore.sh
  addons/clickhouse/dataprotection/restore.sh
  addons/clickhouse/scripts/bootstrap-keeper.sh
  addons/clickhouse/scripts/bootstrap-server.sh
  addons/clickhouse/scripts/member-join.sh
Labels: pick-1.0

#1724 chore: change kafka-exporter repository
  addons/kafka/values.yaml
Labels: pick-0.9, pick-1.0

#1725 fix: redis rebuild instance failed
  addons/redis/redis-cluster-scripts/redis-cluster-common.sh
  addons/redis/redis-cluster-scripts/redis-cluster-server-start.sh
  addons/redis/templates/backuppolicytemplate.yaml
Labels: pick-1.0

#1745 chore: improve nebula addon
  addons-cluster/nebula-cluster/templates/cluster.yaml
  addons-cluster/nebula-cluster/templates/configmap.yaml
  addons/nebula/Chart.yaml
  addons/nebula/configs/nebula-graphd.conf.tpl
  addons/nebula/configs/nebula-metad.conf.tpl
  addons/nebula/scripts/balance-data.py
  addons/nebula/scripts/logrotate.sh
  addons/nebula/scripts/member-leave.py
  addons/nebula/scripts/start-graphd.sh
  addons/nebula/scripts/start-metad.sh
  addons/nebula/scripts/start-storaged.sh
  addons/nebula/templates/_helpers.tpl
  addons/nebula/templates/clusterdefinition.yaml
  addons/nebula/templates/cmpd-graphd.yaml
  addons/nebula/templates/cmpd-metad.yaml
  addons/nebula/templates/cmpd-storaged.yaml
  addons/nebula/templates/cmpv.yaml
  addons/nebula/templates/opsdefinition.yaml
  addons/nebula/templates/scripts-storaged.yaml
  addons/nebula/templates/scripts.yaml
  addons/nebula/values.yaml
Labels: nopick

#1749 chore: tidy up pg cluster chart
  addons-cluster/postgresql/Chart.yaml
  addons-cluster/postgresql/chart
  addons-cluster/postgresql/templates/validate.yaml
  addons-cluster/postgresql/values.yaml
Labels: nopick

#1733 chore: milvus with kafka and etcd included
  addons-cluster/milvus-cluster/Chart.yaml
  addons-cluster/milvus-cluster/templates/_helpers.tpl
  addons-cluster/milvus-cluster/templates/cluster.yaml
  addons-cluster/milvus-cluster/templates/standalone.yaml
  addons-cluster/milvus-cluster/values.yaml
  addons/milvus/Chart.yaml
  addons/milvus/configs/cluster-user.yaml
  addons/milvus/scripts/delegate-run.sh
  addons/milvus/templates/_helpers.tpl
  addons/milvus/templates/clusterdefinition.yaml
  addons/milvus/templates/cmpd-minio.yaml
  addons/milvus/templates/cmpv.yaml
  addons/milvus/templates/componentdefinition-data.yaml
  addons/milvus/templates/componentdefinition-index.yaml
  addons/milvus/templates/componentdefinition-mixcoord.yaml
  addons/milvus/templates/componentdefinition-proxy.yaml
  addons/milvus/templates/componentdefinition-query.yaml
  addons/milvus/templates/componentdefinition-standalone.yaml
  addons/milvus/values.yaml
Labels: nopick

#1753 fix: clickhouse post-for-scale-out-shard.sh failed when no any tables creating
  addons/clickhouse/scripts/post-for-scale-out-shard.sh
Labels: pick-1.0
