Repository apecloud/kubeblocks-addons, pull requests merged in 2025-08, with the labels that each got.

#1854 chore: chagne pg scope label
  addons-cluster/postgresql/templates/_helpers.tpl
  addons/postgresql/README.md
  addons/postgresql/templates/cmpd.yaml
  examples/postgresql/README.md
  examples/postgresql/cluster.yaml
  examples/postgresql/restore.yaml
Labels: pick-1.0

#1834 fix[qdrant]: some data is lost after restore
  addons/qdrant/scripts/qdrant-restore.sh
Labels: nopick

#1861 chore[qdrant]: use kb1.0 api
  addons/qdrant/scripts-ut-spec/qdrant_member_leave_spec.sh
  addons/qdrant/scripts-ut-spec/qdrant_setup_spec.sh
  addons/qdrant/scripts-ut-spec/utils.sh
  addons/qdrant/scripts/qdrant-backup.sh
  addons/qdrant/scripts/qdrant-member-leave.sh
  addons/qdrant/scripts/qdrant-restore.sh
  addons/qdrant/scripts/qdrant-setup.sh
  addons/qdrant/templates/cmpd.yaml
  addons/qdrant/values.yaml
Labels: nopick

#1871 chore: support parameters api for mongodb
  addons/mongodb/templates/_names.tpl
  addons/mongodb/templates/cmpd.yaml
  addons/mongodb/templates/prc.yaml
Labels: pick-1.0

#1868 fix: Failed to create memberlist
  addons/loki/configs/loki-config.tpl
  addons/loki/templates/cmpd-backend.yaml
  addons/loki/templates/cmpd-gateway.yaml
  addons/loki/templates/cmpd-read.yaml
  addons/loki/templates/cmpd-write.yaml
Labels: pick-0.9

#1874 chore: improve pg dcs
  addons/postgresql/config/pg12-config.tpl
  addons/postgresql/config/pg14-config.tpl
  addons/postgresql/config/pg15-config.tpl
  addons/postgresql/config/pg16-config.tpl
  addons/postgresql/config/pg17-config.tpl
  addons/postgresql/scripts/postgres-setup.sh
Labels: pick-1.0

#1881 fix: modify zoocreeper image registry
  addons/zookeeper/templates/_helpers.tpl
  addons/zookeeper/values.yaml
Labels: pick-0.9, pick-1.0

#1870 chore: upgrade rocketmq to KB 1.0
  .github/CODEOWNERS
  README.md
  addons-cluster/rocketmq/.helmignore
  addons-cluster/rocketmq/Chart.yaml
  addons-cluster/rocketmq/templates/_helpers.tpl
  addons-cluster/rocketmq/templates/cluster.yaml
  addons-cluster/rocketmq/values.yaml
  addons/rocketmq/.helmignore
  addons/rocketmq/Chart.yaml
  addons/rocketmq/configs/logback_broker.xml
  addons/rocketmq/configs/logback_namesrv.xml
  addons/rocketmq/configs/logback_tools.xml
  addons/rocketmq/configs/plain_acl.yml
  addons/rocketmq/configs/rocketmq4-broker-config-constraint.cue
  addons/rocketmq/configs/rocketmq4-broker-config-effect-scope.yaml
  addons/rocketmq/configs/rocketmq4-broker-config.tpl
  addons/rocketmq/configs/rocketmq4-namesrv-config.tpl
  addons/rocketmq/reloader/update-broker-parameter.sh
  addons/rocketmq/scripts/broker-setup.sh
  addons/rocketmq/scripts/dashboard-setup.sh
  addons/rocketmq/scripts/exporter-setup.sh
  addons/rocketmq/scripts/get-role.sh
  addons/rocketmq/scripts/nameserver-setup.sh
  addons/rocketmq/scripts/update-nameserver-addrs.sh
  addons/rocketmq/templates/_helpers.tpl
  addons/rocketmq/templates/clusterdefinition.yaml
  addons/rocketmq/templates/cmpd-broker.yaml
  addons/rocketmq/templates/cmpd-dashboard.yaml
  addons/rocketmq/templates/cmpd-exporter.yaml
  addons/rocketmq/templates/cmpd-nameserver.yaml
  addons/rocketmq/templates/cmpv-broker.yaml
  addons/rocketmq/templates/cmpv-dashboard.yaml
  addons/rocketmq/templates/cmpv-exporter.yaml
  addons/rocketmq/templates/cmpv-nameserver.yaml
  addons/rocketmq/templates/configmap-broker.yaml
  addons/rocketmq/templates/configmap-nameserver.yaml
  addons/rocketmq/templates/paramdef-broker.yaml
  addons/rocketmq/templates/pcr-broker.yaml
  addons/rocketmq/templates/scripts.yaml
  addons/rocketmq/templates/sharding-definition.yaml
  addons/rocketmq/values.yaml
Labels: nopick

#1887 chore: support influxdb parameters
  README.md
  addons-cluster/influxdb/Chart.yaml
  addons-cluster/influxdb/values.schema.json
  addons-cluster/influxdb/values.yaml
  addons/influxdb/Chart.yaml
  addons/influxdb/README.md
  addons/influxdb/config/influxdb-config-constraint.cue
  addons/influxdb/config/influxdb-config.tpl
  addons/influxdb/templates/__helpers.tpl
  addons/influxdb/templates/cmpd.yaml
  addons/influxdb/templates/cmpv.yaml
  addons/influxdb/templates/configmap.yaml
  addons/influxdb/templates/paramdef.yaml
  addons/influxdb/templates/pcr.yaml
  addons/influxdb/values.yaml
  examples/influxdb/README.md
  examples/influxdb/cluster.yaml
Labels: nopick

#1888 fix: redis account custom ops
  addons/redis/scripts/redis-account.sh
  addons/redis/templates/_helpers.tpl
  addons/redis/templates/opsdefinition-account.yaml
Labels: pick-1.0

#1886 modify redis-cluster-switchover.sh to stop perform switch over when the pod which should be deleted by scale in oprequest has become primary role by dbctl, fix bug https://github.com/apecloud/kubeblocks/issues/9609
  addons/redis/redis-cluster-scripts/redis-cluster-switchover.sh
  addons/redis/redis-cluster-scripts/redis-cluster6-switchover.sh
Labels: pick-1.0

#1885 chore: milvus pick 0.9 fixes
  README.md
  addons-cluster/milvus/templates/NOTES.txt
  addons-cluster/milvus/templates/_helpers.tpl
  addons-cluster/milvus/templates/cluster.yaml
  addons-cluster/milvus/values.schema.json
  addons-cluster/milvus/values.yaml
  addons/milvus/configs/cluster-user.yaml
  addons/milvus/scripts/delegate-run.sh
  addons/milvus/templates/NOTES.txt
  addons/milvus/templates/_helpers.tpl
  addons/milvus/templates/cmpv.yaml
  addons/milvus/values.yaml
Labels: pick-1.0

#1891 fix: redis cluster mode account ops
  addons/redis/scripts/redis-account.sh
  addons/redis/templates/opsdefinition-account.yaml
Labels: pick-1.0

#1890 chore: support mysql audit log config
  addons/mysql/config/mysql5.7-config-constraint.cue
  addons/mysql/config/mysql5.7-config-effect-scope.yaml
  addons/mysql/config/mysql5.7-config.tpl
  addons/mysql/config/mysql8-config-constraint.cue
  addons/mysql/config/mysql8-config-effect-scope.yaml
  addons/mysql/config/mysql8.0-config.tpl
Labels: pick-1.0

#1894 fix[elasticsearch]: backup failed
  addons/elasticsearch/templates/cmpd-es-7.yaml
  addons/elasticsearch/templates/cmpd-es-8.yaml
Labels: nopick

#1895 fix[elasticsearch]: backup failed
  addons/elasticsearch/templates/cmpd-es-7.yaml
  addons/elasticsearch/templates/cmpd-es-8.yaml
Labels: pick-1.0

#1900 fix: kafka separated mode creation fail
  addons-cluster/kafka/templates/cluster.yaml
Labels: pick-1.0

#1903 chore: ck examples & keeper tls roleprobe
  addons/clickhouse/README.md
  addons/clickhouse/scripts/common.sh
  examples/clickhouse/README.md
  examples/clickhouse/cluster-sharding.yaml
  examples/clickhouse/cluster-standalone.yaml
  examples/clickhouse/cluster-tls.yaml
  examples/clickhouse/cluster-with-nodeport.yaml
  examples/clickhouse/cluster.yaml
  examples/clickhouse/expose-disable.yaml
  examples/clickhouse/expose-enable.yaml
Labels: pick-1.0

#1910 fix: set rocketmq enableDLegerCommitLog & namesrvAddr immutable
  addons/rocketmq/configs/rocketmq4-broker-config-effect-scope.yaml
Labels: pick-0.9, pick-1.0

#1904 chore: do not run pgbouncer as root
  addons/postgresql/scripts/pgbouncer_setup.sh
Labels: nopick

#1905 chore: do not run pgbouncer as root
  addons/postgresql/scripts/pgbouncer-setup.sh
Labels: nopick

#1916 chore: ck metrics09
  addons/clickhouse/Chart.yaml
  addons/clickhouse/dashboards/clickhouse.json
  addons/clickhouse/values.yaml
  addons/etcd/dashboards/etcd.json
Labels: nopick

#1911 fix: ck & etcd dashboard and add ck env
  addons/clickhouse/README.md
  addons/clickhouse/dashboards/clickhouse.json
  addons/clickhouse/templates/cmpd-ch.yaml
  addons/clickhouse/templates/cmpd-keeper.yaml
  addons/clickhouse/values.yaml
  addons/etcd/dashboards/etcd.json
  examples/clickhouse/README.md
  examples/clickhouse/post-scale-out-shard.yaml
  examples/clickhouse/scale-in-sharding.yaml
  examples/clickhouse/scale-out-sharding.yaml
Labels: pick-1.0

#1918 fix[qdrant]: create cluster pending
  addons/qdrant/scripts/qdrant-setup.sh
  addons/qdrant/templates/cmpd.yaml
Labels: pick-1.0

#1920 chore: pg getrole by http
  addons/postgresql/templates/cmpd.yaml
  addons/postgresql/templates/cmpv.yaml
  addons/postgresql/values.yaml
Labels: pick-1.0

#1917 chore: fix postgresql pgbouncer scripts
  addons/postgresql/scripts-ut-spec/pgbouncer_setup_spec.sh
  addons/postgresql/scripts/pgbouncer-setup.sh
Labels: pick-1.0

#1924 fix: rocketmq namesrv hscale
  addons/rocketmq/scripts/update-nameserver-addrs.sh
  addons/rocketmq/templates/cmpd-nameserver.yaml
Labels: pick-1.0

#1915 feat: loki s3 support with serviceRef
  addons-cluster/loki/templates/_helpers.tpl
  addons-cluster/loki/templates/cluster.yaml
  addons-cluster/loki/values.yaml
  addons/loki/README.md
  addons/loki/configs/loki-config.tpl
  addons/loki/templates/_helpers.tpl
  addons/loki/templates/cmpd-backend.yaml
  addons/loki/templates/cmpd-read.yaml
  addons/loki/templates/cmpd-write.yaml
  addons/loki/values.yaml
  examples/loki/README.md
Labels: pick-1.0

#1925 fix: clickhouse standalone create failed
  addons/clickhouse/templates/clusterdefinition.yaml
Labels: pick-1.0

#1923 feat[elasticsearch]: support new version 8.15.5
  README.md
  addons/elasticsearch/templates/_helpers.tpl
  addons/elasticsearch/templates/cmpd-kibana-8.yaml
  addons/elasticsearch/templates/cmpv-es.yaml
  addons/elasticsearch/templates/cmpv-kibana.yaml
Labels: pick-0.9, pick-1.0

#1929 feat[elasticsearch]: support new version 8.15.5
  addons/elasticsearch/templates/_helpers.tpl
  addons/elasticsearch/templates/cmpv-es.yaml
  addons/elasticsearch/templates/cmpv-kibana.yaml
Labels: nopick

#1936 chore: add slave_preserve_commit_order to cc
  addons/mysql/config/mysql5.7-config-constraint.cue
  addons/mysql/config/mysql5.7-config-effect-scope.yaml
Labels: pick-0.9, pick-1.0

#1940 fix: pg restore failed from wal-g
  addons/postgresql/scripts/generate_patroni_yaml.py
Labels: pick-0.9, pick-1.0

#1941 chore: pg support synchronous mode
  addons/postgresql/scripts/generate_patroni_yaml.py
Labels: pick-0.9, pick-1.0

#1944 fix: mongodb sharding backup failed
  addons/mongodb/dataprotection/shard-pbm-pre-backup.sh
  addons/mongodb/scripts/mongodb-shard-manage.sh
Labels: pick-0.9, pick-1.0

#1945 chore: fix orioledb restart crash
  addons/orioledb/config/pg16-config.tpl
Labels: pick-1.0

#1947 chore: restart pg when istance is in archive recovery to trigger pg rewind
  addons/postgresql/scripts/postgres-setup.sh
Labels: pick-1.0

#1946 Revert "fix: pg restore failed from wal-g"
  addons/postgresql/scripts/generate_patroni_yaml.py
Labels: pick-0.9, pick-1.0
