Repository apecloud/kubeblocks-addons, pull requests merged in 2025-03, with the labels that each got.

#1317 chore: support parameters api for redis
  addons/redis/templates/_helpers.tpl
  addons/redis/templates/cmpd-redis-7.yaml
  addons/redis/templates/cmpd-redis-cluster-7.yaml
  addons/redis/templates/paramsdef-redis-cluster7.yaml
  addons/redis/templates/paramsdef-redis7.yaml
  addons/redis/templates/pcr-redis-cluster.yaml
  addons/redis/templates/pcr-redis.yaml
Labels: parameter/apis

#1373 chore: support parameters api for loki
  addons-cluster/loki/templates/_helpers.tpl
  addons-cluster/loki/templates/cluster.yaml
  addons-cluster/loki/templates/configmap-gateway.yaml
  addons-cluster/loki/templates/configmap.yaml
  addons-cluster/loki/templates/runtime-configmap.yaml
  addons-cluster/loki/values.yaml
  addons/loki/configs/loki-config.tpl
  addons/loki/configs/loki-gateway-config.tpl
  addons/loki/configs/loki-runtime-config.tpl
  addons/loki/templates/_helpers.tpl
  addons/loki/templates/clusterdefinition.yaml
  addons/loki/templates/cmpd-backend.yaml
  addons/loki/templates/cmpd-gateway.yaml
  addons/loki/templates/cmpd-read.yaml
  addons/loki/templates/cmpd-write.yaml
  addons/loki/templates/cmpv.yaml
  addons/loki/templates/configmap.yaml
  addons/loki/templates/pcr-backend.yaml
  addons/loki/templates/pcr-read.yaml
  addons/loki/templates/pcr-write.yaml
  addons/loki/values.yaml
Labels: bug, parameter/apis

#1372 chore: support parameters api for clickhouse
  addons/clickhouse/templates/_helpers.tpl
  addons/clickhouse/templates/cmpd-clickhouse.yaml
  addons/clickhouse/templates/paramsdef.yaml
  addons/clickhouse/templates/pcr.yaml
Labels: bug, parameter/apis

#1371 chore: support parameters api for qdrant
  addons/qdrant/templates/_helpers.tpl
  addons/qdrant/templates/componentdefinition.yaml
  addons/qdrant/templates/configconstraint.yaml
  addons/qdrant/templates/pcr.yaml
Labels: parameter/apis

#1370 chore: support parameters api for elasticsearch
  addons/elasticsearch/templates/_helpers.tpl
  addons/elasticsearch/templates/pcr-7.yaml
  addons/elasticsearch/templates/pcr-8.yaml
Labels: parameter/apis

#1369 chore: support parameters api for kafka
  addons/kafka/templates/_helpers.tpl
  addons/kafka/templates/cmpd-broker-27.yaml
  addons/kafka/templates/cmpd-broker.yaml
  addons/kafka/templates/cmpd-combine.yaml
  addons/kafka/templates/cmpd-controller.yaml
  addons/kafka/templates/configconstraint.yaml
  addons/kafka/templates/paramsdef.yaml
  addons/kafka/templates/paramsdef2.yaml
  addons/kafka/templates/pcr-broker.yaml
  addons/kafka/templates/pcr-broker2.yaml
  addons/kafka/templates/pcr-combine.yaml
  addons/kafka/templates/pcr-controller.yaml
Labels: parameter/apis

#1320 chore: support parameters api for postgresql
  addons/postgresql/templates/_helpers.tpl
  addons/postgresql/templates/componentdefinition-12.yaml
  addons/postgresql/templates/componentdefinition-14.yaml
  addons/postgresql/templates/componentdefinition-15.yaml
  addons/postgresql/templates/componentdefinition-16.yaml
  addons/postgresql/templates/configmap-12.yaml
  addons/postgresql/templates/configmap-14.yaml
  addons/postgresql/templates/configmap-15.yaml
  addons/postgresql/templates/configmap-16.yaml
  addons/postgresql/templates/paramsdef-12.yaml
  addons/postgresql/templates/paramsdef-14.yaml
  addons/postgresql/templates/paramsdef-15.yaml
  addons/postgresql/templates/paramsdef-16.yaml
  addons/postgresql/templates/paramsdef-patroni.yaml
  addons/postgresql/templates/pcr-12.yaml
  addons/postgresql/templates/pcr-14.yaml
  addons/postgresql/templates/pcr-15.yaml
  addons/postgresql/templates/pcr-16.yaml
Labels: parameter/apis

#1319 chore: support parameters api for mongodb
  addons/mongodb/templates/_names.tpl
  addons/mongodb/templates/componentdefinition.yaml
  addons/mongodb/templates/configconstraint.yaml
  addons/mongodb/templates/configtemplate.yaml
  addons/mongodb/templates/pcr.yaml
Labels: parameter/apis

#1318 chore: support parameters api for etcd
  addons/etcd/templates/_helpers.tpl
  addons/etcd/templates/pcr.yaml
Labels: parameter/apis

#1316 chore: support parameters api for apecloud-mysql
  addons/apecloud-mysql/templates/_names.tpl
  addons/apecloud-mysql/templates/cmpd-apecloudmysql.yaml
  addons/apecloud-mysql/templates/cmpd-wescale.yaml
  addons/apecloud-mysql/templates/configconstraint.yaml
  addons/apecloud-mysql/templates/pcr-wescale.yaml
  addons/apecloud-mysql/templates/pcr-wesql.yaml
  addons/apecloud-mysql/templates/pd-wescale.yaml
  addons/apecloud-mysql/templates/pd-wesql-vttablet.yaml
  addons/apecloud-mysql/templates/pd-wesql.yaml
Labels: parameter/apis

#1315 chore: support parameters api for mysql
  addons/mysql/templates/_names.tpl
  addons/mysql/templates/cmpd-mysql57-orc.yaml
  addons/mysql/templates/cmpd-mysql57.yaml
  addons/mysql/templates/cmpd-mysql80-mgr.yaml
  addons/mysql/templates/cmpd-mysql80-orc.yaml
  addons/mysql/templates/cmpd-mysql80.yaml
  addons/mysql/templates/cmpd-mysql84-mgr.yaml
  addons/mysql/templates/cmpd-mysql84.yaml
  addons/mysql/templates/cmpd-proxysql.yaml
  addons/mysql/templates/paramsdef-57.yaml
  addons/mysql/templates/paramsdef-80.yaml
  addons/mysql/templates/pcr-57-orc.yaml
  addons/mysql/templates/pcr-57.yaml
  addons/mysql/templates/pcr-80-mgr.yaml
  addons/mysql/templates/pcr-80-orc.yaml
  addons/mysql/templates/pcr-80.yaml
  addons/mysql/templates/pcr-84-mgr.yaml
  addons/mysql/templates/pcr-84.yaml
Labels: parameter/apis

#1507 chore: update parameters api docs
  addons/apecloud-mysql/README.md
  addons/clickhouse/README.md
  addons/kafka/README.md
  addons/mogdb/README.md
  addons/mongodb/README.md
  addons/mysql/README.md
  addons/oceanbase-ce/README.md
  addons/orioledb/README.md
  addons/postgresql/README.md
  addons/pulsar/README.md
  addons/rabbitmq/README.md
  addons/redis/README.md
  addons/risingwave/README.md
  addons/vanilla-postgresql/README.md
  addons/weaviate/README.md
  addons/zookeeper/README.md
  examples/apecloud-mysql/configure-vtgate.yaml
  examples/apecloud-mysql/configure-vttablet.yaml
  examples/apecloud-mysql/configure.yaml
  examples/apecloud-mysql/smartengine-disable.yaml
  examples/apecloud-mysql/smartengine-enable.yaml
  examples/clickhouse/README.md
  examples/clickhouse/configure.yaml
  examples/kafka/configure.yaml
  examples/mogdb/configure.yaml
  examples/mongodb/configure.yaml
  examples/mysql/configure.yaml
  examples/oceanbase-ce/configure.yaml
  examples/postgresql/configure.yaml
  examples/postgresql/reconfig-arhive-command.yaml
  examples/pulsar/configure.yaml
  examples/rabbitmq/reconfigure.yaml
  examples/redis/configure.yaml
  examples/redis/reconfigure-aof.yaml
  examples/vanilla-postgresql/configure.yaml
  examples/weaviate/configure.yaml
  examples/zookeeper/configure.yaml
Labels: parameter/apis

#1508 chore: support parameters api for rabbitmq
  addons/rabbitmq/templates/_names.tpl
  addons/rabbitmq/templates/componentdefinition.yaml
  addons/rabbitmq/templates/configconstraint.yaml
  addons/rabbitmq/templates/paramsdef.yaml
  addons/rabbitmq/templates/pcr.yaml
Labels: parameter/apis

#1523 chore: add auto cherry-pick workflow
  .github/workflows/cherry-pick-auto.yml
  .github/workflows/cherry-pick-label-check.yml
  .github/workflows/cherry-pick-usage.yml
  .github/workflows/cherry-pick.yml
Labels: pick-0.9

#1527 chore: fix comment actions error
  .github/workflows/cherry-pick.yml
Labels: pick

#1528 chore: minio add replicas limit
  addons/minio/templates/cmpd.yaml
Labels: nopick

#1530 chore: fix no matched image found for container init-syncer
  addons/orioledb/templates/cmpv.yaml
Labels: pick-1.0-beta

#1524 fix: mysql orc errors
  addons-cluster/mysql/templates/cluster.yaml
  addons-cluster/mysql/values.yaml
  addons/mysql/scripts/init-mysql-instance-for-orc.sh
  addons/mysql/templates/_helpers.tpl
  addons/mysql/templates/_orc.tpl
Labels: nopick

#1531 chore: update promtail values and add Alloy deployment
  examples/docs/install-plg-stack.md
  examples/docs/misc/alloy.config
  examples/docs/misc/alloy.values.yaml
  examples/docs/misc/plg-stack-values-sample.yaml
  examples/docs/misc/promtail.config
  examples/loki/cluster.yaml
  examples/loki/test/loki-query.py
  examples/loki/test/loki-write.py
Labels: pick-1.0-beta

#1533 fix: update etcd config and roleProbe
  addons/etcd/config/etcd.conf.yaml.tpl
  addons/etcd/scripts-ut-spec/common_spec.sh
  addons/etcd/scripts/common.sh
  examples/docs/install-plg-stack.md
  examples/etcd/README.md
  examples/etcd/cluster-with-tls.yaml
Labels: pick-1.0-beta

#1535 fix: add minSessionTimeout for zookeeper
  addons/zookeeper/config/zookeeper-config.tpl
  addons/zookeeper/config/zookeeper-params_schema.cue
Labels: pick-0.9

#1532 chore: new scripts API in the cmpd
  addons/apecloud-mysql/templates/_helpers.tpl
  addons/apecloud-mysql/templates/cmpd-wescale-controller.yaml
  addons/apecloud-mysql/templates/cmpd-wescale.yaml
  addons/apecloud-postgresql/templates/cmpd-apepg.yaml
  addons/elasticsearch/templates/cmpd-7.yaml
  addons/elasticsearch/templates/cmpd-8.yaml
  addons/etcd/templates/cmpd.yaml
  addons/kafka/templates/cmpd-broker-27.yaml
  addons/kafka/templates/cmpd-broker.yaml
  addons/kafka/templates/cmpd-combine.yaml
  addons/kafka/templates/cmpd-controller.yaml
  addons/kafka/templates/cmpd-exporter.yaml
  addons/llm/templates/cmpd-ggml.yaml
  addons/llm/templates/cmpd-vllm.yaml
  addons/minio/templates/cmpd.yaml
  addons/mogdb/templates/cmpd.yaml
  addons/mongodb/templates/componentdefinition.yaml
  addons/mysql/templates/_helpers.tpl
  addons/mysql/templates/_orc.tpl
  addons/mysql/templates/cmpd-proxysql.yaml
  addons/nebula/templates/cmpd-storaged.yaml
  addons/neon/templates/cmpd-compute.yaml
  addons/neon/templates/cmpd-pageserver.yaml
  addons/neon/templates/cmpd-safekeeper.yaml
  addons/oceanbase-ce/templates/_helpers.tpl
  addons/opensearch/templates/cmpd.yaml
  addons/orchestrator/templates/_helpers.tpl
  addons/orioledb/templates/cmpd.yaml
  addons/polardbx/templates/cmpd-cdc.yaml
  addons/polardbx/templates/cmpd-cn.yaml
  addons/polardbx/templates/cmpd-dn.yaml
  addons/polardbx/templates/cmpd-gms.yaml
  addons/postgresql/templates/componentdefinition-12.yaml
  addons/postgresql/templates/componentdefinition-14.yaml
  addons/postgresql/templates/componentdefinition-15.yaml
  addons/postgresql/templates/componentdefinition-16.yaml
  addons/pulsar/templates/cmpd-bookies-recovery-2.yaml
  addons/pulsar/templates/cmpd-bookies-recovery-3.yaml
  addons/pulsar/templates/cmpd-bookkeeper-2.yaml
  addons/pulsar/templates/cmpd-bookkeeper-3.yaml
  addons/pulsar/templates/cmpd-broker-2.yaml
  addons/pulsar/templates/cmpd-broker-3.yaml
  addons/pulsar/templates/cmpd-proxy-2.yaml
  addons/pulsar/templates/cmpd-proxy-3.yaml
  addons/pulsar/templates/cmpd-zookeeper-2.yaml
  addons/pulsar/templates/cmpd-zookeeper-3.yaml
  addons/qdrant/templates/componentdefinition.yaml
  addons/redis/templates/cmpd-redis-7.yaml
  addons/redis/templates/cmpd-redis-cluster-7.yaml
  addons/redis/templates/cmpd-redis-sentinel-7.yaml
  addons/redis/templates/cmpd-redis-twemproxy.yaml
  addons/starrocks-ce/templates/componentdefinition-fe.yaml
  addons/tdengine/templates/cmpd.yaml
  addons/tidb/templates/componentdefinition-pd.yaml
  addons/vanilla-postgresql/templates/cmpd-12.yaml
  addons/vanilla-postgresql/templates/cmpd-14.yaml
  addons/vanilla-postgresql/templates/cmpd-15.yaml
  addons/xinference/templates/cmpd.yaml
  addons/yashandb/templates/cmpd.yaml
  addons/zookeeper/templates/cmpd.yaml
Labels: pick-1.0-beta

#1538 fix: kbcli create ck failed
  addons-cluster/clickhouse/values.schema.json
Labels: pick-1.0-beta

#1537 kafka's jmx-exporter support custom envs and port
  addons/kafka/templates/cmpd-broker-27.yaml
  addons/kafka/templates/cmpd-broker.yaml
  addons/kafka/templates/cmpd-combine.yaml
  addons/kafka/templates/cmpd-controller.yaml
  addons/kafka/values.yaml
Labels: pick-1.0-beta

#1534 fix: align target instance of mysql inc backup
  addons/apecloud-mysql/dataprotection/backup.sh
  addons/apecloud-mysql/dataprotection/xtrabackup-incremental-backup.sh
  addons/apecloud-mysql/dataprotection/xtrabackup-incremental-restore.sh
  addons/mysql/dataprotection/backup.sh
  addons/mysql/dataprotection/xtrabackup-incremental-backup.sh
  addons/mysql/dataprotection/xtrabackup-incremental-restore.sh
Labels: nopick

#1541 fix: mysql orc member leave error
  addons/mysql/templates/_orc.tpl
Labels: pick-1.0-beta

#1544 support customise kafka's prometheus metric export config
  addons/kafka/configs/jmx-kafka-prometheus.yml
  addons/kafka/templates/configuration-template.yaml
  addons/kafka/values.yaml
Labels: pick-1.0-beta

#1553 chore: remove grafana configmap from addons
  addons/apecloud-mysql/templates/grafana/configmap-dashboards.yaml
  addons/clickhouse/templates/grafana/configmap-dashboards.yaml
  addons/elasticsearch/templates/grafana/configmap-dashboards.yaml
  addons/etcd/templates/grafana/configmap-dashboards.yaml
  addons/kafka/templates/grafana/configmap-dashboards.yaml
  addons/mariadb/templates/grafana/configmap-dashboards.yaml
  addons/mogdb/templates/grafana/configmap-dashboards.yaml
  addons/mongodb/templates/grafana/configmap-dashboards.yaml
  addons/oceanbase-ce/templates/grafana/configmap-dashboards.yaml
  addons/postgresql/templates/grafana/configmap-dashboards.yaml
  addons/pulsar/templates/grafana/configmap-dashboards.yaml
  addons/qdrant/templates/grafana/configmap-dashboards.yaml
  addons/redis/templates/grafana/configmap-dashboards.yaml
  addons/tdengine/templates/grafana/configmap-dashboards.yaml
  addons/tidb/templates/grafana/configmap-dashboards.yaml
  addons/victoria-metrics/templates/grafana/configmap-dashboards.yaml
  addons/weaviate/templates/grafana/configmap-dashboards.yaml
Labels: pick-1.0-beta

#1556 chore: tidy up cmpd name
  addons-cluster/orchestrator/templates/cluster.yaml
  addons-cluster/orchestrator/values.schema.json
  addons-cluster/orchestrator/values.yaml
  addons/llm/templates/_helpers.tpl
  addons/llm/templates/cmpd-ggml.yaml
  addons/llm/templates/cmpd-vllm.yaml
  addons/orchestrator/README.md
  addons/orchestrator/templates/_helpers.tpl
  addons/orchestrator/templates/clusterdefinition.yaml
  addons/orchestrator/templates/cmpd-raft.yaml
  addons/orchestrator/templates/cmpd-shared-backend.yaml
  addons/orchestrator/templates/cmpv.yaml
  examples/orchestrator/README.md
  examples/orchestrator/cluster-shared-backend.yaml
Labels: pick-1.0-beta

#1559 chore: fix orioledb ops
  addons/orioledb/templates/_helpers.tpl
Labels: pick-1.0-beta

#1555 chore: redis cluster stop-start re-meet all nodes
  addons/redis/redis-cluster-scripts/redis-cluster-common.sh
  addons/redis/redis-cluster-scripts/redis-cluster-server-start.sh
  addons/redis/scripts-ut-spec/redis_cluster_server_start_spec.sh
Labels: pick-1.0-beta
