Repository apecloud/kubeblocks-addons, pull requests merged in 2025-04, with the labels that each got.

#1560 chore: persist log files for clickhouse and keeper
  addons/clickhouse/configs/00_default_overrides.xml.tpl
  addons/clickhouse/configs/ch_keeper_00_default_overrides.xml.tpl
Labels: pick-1.0-beta

#1561 chore: change switchover example
  addons/apecloud-postgresql/README.md
  addons/clickhouse/README.md
  addons/mongodb/README.md
  addons/mysql/README.md
  addons/postgresql/README.md
  addons/victoria-metrics/README.md
  addons/zookeeper/README.md
  examples/apecloud-mysql/switchover-specified-instance.yaml
  examples/apecloud-mysql/switchover.yaml
  examples/apecloud-postgresql/switchover.yaml
  examples/etcd/switchover.yaml
  examples/mongodb/switchover-specified-instance.yaml
  examples/mongodb/switchover.yaml
  examples/mysql/README.md
  examples/mysql/switchover-specified-instance.yaml
  examples/mysql/switchover.yaml
  examples/postgresql/switchover-specified-instance.yaml
  examples/postgresql/switchover.yaml
  examples/redis/switchover-specified-instance.yaml
  examples/redis/switchover.yaml
  examples/vanilla-postgresql/switchover-specified-instance.yaml
  examples/vanilla-postgresql/switchover.yaml
Labels: pick-1.0-beta

#1565 chore: fix etcd examples cluster-tls.yaml not found
  addons/apecloud-mysql/README.md
  addons/etcd/README.md
  addons/milvus/README.md
  addons/vanilla-postgresql/README.md
  examples/etcd/README.md
Labels: pick-1.0-beta

#1570 chore: support pgbouncer-configuration reconfigure
  addons/postgresql/templates/pcr-12.yaml
  addons/postgresql/templates/pcr-14.yaml
  addons/postgresql/templates/pcr-15.yaml
  addons/postgresql/templates/pcr-16.yaml
Labels: pick-1.0-beta

#1522 feat[elasticsearch]: security enhancement
  addons-cluster/elasticsearch-cluster/Chart.yaml
  addons-cluster/elasticsearch-cluster/templates/_helpers.tpl
  addons-cluster/elasticsearch-cluster/templates/cluster-multi-node.yaml
  addons-cluster/elasticsearch-cluster/templates/cluster-single-node.yaml
  addons-cluster/elasticsearch-cluster/values.schema.json
  addons-cluster/elasticsearch-cluster/values.yaml
  addons/elasticsearch/Chart.yaml
  addons/elasticsearch/configs/elasticsearch-7-log4j2.properties
  addons/elasticsearch/configs/elasticsearch-7.yml.tpl
  addons/elasticsearch/configs/elasticsearch-8.yml.tpl
  addons/elasticsearch/configs/kibana.yml.tpl
  addons/elasticsearch/scripts/post-start-hook.sh
  addons/elasticsearch/scripts/pre-stop-hook.sh
  addons/elasticsearch/scripts/prepare-fs.sh
  addons/elasticsearch/scripts/readiness-probe-script.sh
  addons/elasticsearch/templates/_helpers.tpl
  addons/elasticsearch/templates/componentdefinition-elasticsearch.yaml
  addons/elasticsearch/templates/componentdefinition-kibana.yaml
  addons/elasticsearch/templates/componentversion-elasticsearch.yaml
  addons/elasticsearch/templates/componentversion-kibana.yaml
  addons/elasticsearch/templates/configmap.yaml
  addons/elasticsearch/templates/scripts.yaml
  addons/elasticsearch/values.yaml
Labels: nopick

#1573 chore: update redis sentinel storageClassName field
  addons-cluster/redis/templates/_helpers.tpl
Labels: pick-1.0-beta

#1571 chore: update mysql audit log to exclude only kbadmin
  addons/mysql/config/mysql5.7-config.tpl
  addons/mysql/config/mysql8.0-config.tpl
Labels: pick-1.0-beta

#1572 fix: new config api render failed
  addons/clickhouse/templates/_helpers.tpl
  addons/clickhouse/templates/pcr-keeper.yaml
  addons/mysql/templates/_names.tpl
  addons/mysql/templates/pcr-proxy.yaml
  addons/zookeeper/templates/_helpers.tpl
  addons/zookeeper/templates/pcr.yaml
Labels: pick-1.0-beta

#1574 chore: redis cluster supports configs external managed
  addons-cluster/redis/templates/_helpers.tpl
  addons/mysql/README.md
  addons/redis/README.md
  examples/redis/cluster-sharding.yaml
  examples/redis/cluster-standalone.yaml
  examples/redis/cluster-twemproxy.yaml
  examples/redis/cluster.yaml
Labels: pick-1.0-beta

#1585 chore: update mysql secure_file_priv effect scope
  addons/apecloud-mysql/config/mysql8-config-effect-scope.yaml
  addons/mysql/config/mysql5.7-config-effect-scope.yaml
  addons/mysql/config/mysql8-config-effect-scope.yaml
Labels: pick-1.0-beta

#1579 chore: refine the loki config template
  addons-cluster/loki/templates/_helpers.tpl
  addons/loki/configs/loki-config.tpl
Labels: pick-1.0-beta

#1577 chore: refine the rmq config template
  addons/rabbitmq/config/rabbitmq-config.tpl
Labels: pick-1.0-beta

#1578 chore: refine the risingwave config template
  addons/risingwave/config/risingwave-compute-envs.tpl
  addons/risingwave/config/risingwave-connector-envs.tpl
  addons/risingwave/templates/_helpers.tpl
  addons/risingwave/templates/cmpd-compute.yaml
  addons/risingwave/templates/cmpd-connector.yaml
  addons/risingwave/templates/compute-envs-configuration-template.yaml
  addons/risingwave/templates/connector-envs-configuration-template.yaml
Labels: pick-1.0-beta

#1580 chore: refine the mongodb config template
  addons/mongodb/config/metrics-config.tpl
  addons/mongodb/config/mongodb-env.tpl
  addons/mongodb/config/mongodb5.0-config.tpl
  addons/mongodb/templates/_names.tpl
  addons/mongodb/templates/metrics-configmap.yaml
Labels: pick-1.0-beta

#1582 chore: refine the yashandb config template
  addons/yashandb/configs/install.ini.tpl
  addons/yashandb/templates/cmpd.yaml
Labels: pick-1.0-beta

#1584 chore: refine the redis config template
  addons/redis/config/redis-cluster7-config.tpl
  addons/redis/config/redis7-config.tpl
  addons/redis/templates/cmpd-redis-7.yaml
  addons/redis/templates/cmpd-redis-cluster-7.yaml
Labels: pick-1.0-beta

#1583 chore: refine the orioledb config template
  addons/orioledb/config/pg16-config.tpl
  addons/orioledb/templates/_helpers.tpl
Labels: pick-1.0-beta

#1586 chore: set to restart the pod when the config changes
  addons/clickhouse/templates/cmpd-ch-keeper.yaml
  addons/clickhouse/templates/cmpd-clickhouse.yaml
  addons/elasticsearch/templates/cmpd-7.yaml
  addons/elasticsearch/templates/cmpd-8.yaml
  addons/etcd/templates/cmpd.yaml
  addons/greptimedb/templates/cmpd-datanode.yaml
  addons/greptimedb/templates/cmpd-frontend.yaml
  addons/greptimedb/templates/cmpd-meta.yaml
  addons/kafka/templates/cmpd-broker-27.yaml
  addons/kafka/templates/cmpd-broker.yaml
  addons/kafka/templates/cmpd-combine.yaml
  addons/kafka/templates/cmpd-controller.yaml
  addons/loki/templates/cmpd-backend.yaml
  addons/loki/templates/cmpd-gateway.yaml
  addons/loki/templates/cmpd-read.yaml
  addons/loki/templates/cmpd-write.yaml
  addons/milvus/templates/_helpers.tpl
  addons/minio/templates/cmpd.yaml
  addons/mogdb/templates/cmpd.yaml
  addons/mongodb/templates/cmpd.yaml
  addons/nebula/templates/cmpd-graphd.yaml
  addons/nebula/templates/cmpd-metad.yaml
  addons/nebula/templates/cmpd-storaged.yaml
  addons/neon/templates/cmpd-compute.yaml
  addons/opensearch/templates/cmpd.yaml
  addons/orchestrator/templates/_helpers.tpl
  addons/orioledb/templates/cmpd.yaml
  addons/qdrant/templates/cmpd.yaml
  addons/rabbitmq/templates/cmpd.yaml
  addons/risingwave/templates/_helpers.tpl
  addons/starrocks-ce/templates/cmpd-be.yaml
  addons/starrocks-ce/templates/cmpd-fe.yaml
  addons/tdengine/templates/cmpd.yaml
  addons/weaviate/templates/cmpd.yaml
  addons/yashandb/templates/cmpd.yaml
  addons/zookeeper/templates/cmpd.yaml
Labels: pick-1.0-beta

#1589 chore: set the pod management policy of weative to parallel
  addons/weaviate/templates/cmpd.yaml
Labels: pick-1.0-beta

#1588 chore: update apecloud-mysql/mysql/pg/redis/tidb/v-pg/ob
  addons/apecloud-mysql/templates/cmpd-apecloudmysql.yaml
  addons/apecloud-mysql/templates/cmpd-wescale.yaml
  addons/clickhouse/templates/pcr.yaml
  addons/llm/templates/clusterdefinition.yaml
  addons/mysql/templates/cmpd-mysql57-orc.yaml
  addons/mysql/templates/cmpd-mysql57.yaml
  addons/mysql/templates/cmpd-mysql80-mgr.yaml
  addons/mysql/templates/cmpd-mysql80-orc.yaml
  addons/mysql/templates/cmpd-mysql80.yaml
  addons/mysql/templates/cmpd-mysql84-mgr.yaml
  addons/mysql/templates/cmpd-mysql84.yaml
  addons/mysql/templates/pcr-proxy.yaml
  addons/oceanbase-ce/templates/_helpers.tpl
  addons/orioledb/templates/_helpers.tpl
  addons/postgresql/templates/cmpd-12.yaml
  addons/postgresql/templates/cmpd-14.yaml
  addons/postgresql/templates/cmpd-15.yaml
  addons/postgresql/templates/cmpd-16.yaml
  addons/redis/templates/cmpd-redis-7.yaml
  addons/redis/templates/cmpd-redis-cluster-7.yaml
  addons/tidb/templates/cmpd-pd.yaml
  addons/vanilla-postgresql/templates/cmpd-12.yaml
  addons/vanilla-postgresql/templates/cmpd-14.yaml
  addons/vanilla-postgresql/templates/cmpd-15.yaml
  addons/vanilla-postgresql/templates/pcr-12.yaml
  addons/vanilla-postgresql/templates/pcr-14.yaml
  addons/vanilla-postgresql/templates/pcr-15-supabase.yaml
  addons/vanilla-postgresql/templates/pcr-15.yaml
Labels: pick-1.0-beta

#1587 revert redis cluster external managed config
  addons-cluster/redis/templates/_helpers.tpl
  addons/redis/README.md
  examples/redis/cluster-sharding.yaml
  examples/redis/cluster-standalone.yaml
  examples/redis/cluster-twemproxy.yaml
  examples/redis/cluster.yaml
Labels: pick-1.0-beta

#1594 chore: fix tpl render error in clickhouse and mongodb
  addons/clickhouse/configs/00_default_overrides.xml.tpl
  addons/clickhouse/configs/ch_keeper_00_default_overrides.xml.tpl
  addons/clickhouse/templates/cmpd-clickhouse.yaml
  addons/mongodb/config/mongodb5.0-config.tpl
Labels: pick-1.0-beta

#1590 feat: add mongodb new versions
  README.md
  addons-cluster/mongodb/values.schema.json
  addons/mongodb/templates/cmpv.yaml
Labels: pick-1.0-beta

#1598 chore: update tpl for opensearch and pulsar
  addons/pulsar/config/2.11.2/bookies-config.tpl
  addons/pulsar/config/3.0.2/bookies-config.tpl
  addons/pulsar/config/pulsar-env-optimize.tpl
  addons/pulsar/config/pulsar-env.tpl
  addons/pulsar/templates/cmpd-bookies-recovery-2.yaml
  addons/pulsar/templates/cmpd-bookies-recovery-3.yaml
  addons/pulsar/templates/cmpd-bookkeeper-2.yaml
  addons/pulsar/templates/cmpd-bookkeeper-3.yaml
  addons/pulsar/templates/cmpd-broker-2.yaml
  addons/pulsar/templates/cmpd-broker-3.yaml
  addons/pulsar/templates/cmpd-proxy-2.yaml
  addons/pulsar/templates/cmpd-proxy-3.yaml
  addons/pulsar/templates/cmpd-zookeeper-2.yaml
  addons/pulsar/templates/cmpd-zookeeper-3.yaml
Labels: pick-1.0-beta

#1601 chore: update pulsar tools image
  addons/pulsar/README.md
  addons/pulsar/templates/_helpers.tpl
  addons/pulsar/templates/config/paramsdef-broker-2.yaml
  addons/pulsar/templates/config/paramsdef-broker-3.yaml
  examples/pulsar/README.md
  examples/pulsar/reconfigure-broker.yaml
Labels: pick-1.0-beta

#1605 chore: upgrade runs version ubuntu-latest
  .github/workflows/shellspec-push.yml
Labels: pick-0.9, pick-1.0-beta

#1597 chore: remove runtime objects from the config template
  addons/elasticsearch/configs/elasticsearch-7.yml.tpl
  addons/elasticsearch/configs/elasticsearch-8.yml.tpl
  addons/elasticsearch/templates/cmpd-7.yaml
  addons/elasticsearch/templates/cmpd-8.yaml
  addons/loki/configs/loki-config.tpl
  addons/loki/configs/loki-gateway-config.tpl
  addons/loki/templates/cmpd-backend.yaml
  addons/loki/templates/cmpd-gateway.yaml
  addons/loki/templates/cmpd-read.yaml
  addons/loki/templates/cmpd-write.yaml
  addons/opensearch/configs/opensearch.yaml.tpl
Labels: pick-1.0-beta

#1607 chore: remove pcr from loki backend/read/write
  addons-cluster/loki/templates/_helpers.tpl
  addons-cluster/loki/templates/cluster.yaml
  addons/loki/README.md
  addons/loki/configs/loki-config.tpl
  addons/loki/templates/pcr-backend.yaml
  addons/loki/templates/pcr-read.yaml
  addons/loki/templates/pcr-write.yaml
  examples/loki/cluster.yaml
Labels: pick-1.0-beta

#1596 feat: add rabbitmq versions
  README.md
  addons-cluster/rabbitmq/values.schema.json
  addons/mongodb/config/keyfile.tpl
  addons/mongodb/templates/cmpd.yaml
  addons/mongodb/values.yaml
  addons/rabbitmq/config/erlang.cookie.tpl
  addons/rabbitmq/templates/cmpd.yaml
  addons/rabbitmq/templates/cmpv.yaml
Labels: pick-1.0-beta

#1604 chore: update ns in svc to demo
  addons/loki/README.md
  addons/minio/README.md
  addons/neon/README.md
  addons/risingwave/README.md
  addons/victoria-metrics/README.md
  addons/zookeeper/README.md
  examples/kafka/cluster-2x-ext-zk-svc-descriptor.yaml
  examples/loki/README.md
  examples/minio/README.md
  examples/neon/cluster.yaml
  examples/risingwave/README.md
  examples/risingwave/cluster.yaml
  examples/victoria-metrics/README.md
  examples/zookeeper/README.md
Labels: pick-1.0-beta

#1610 chore: clean up useless parameter CRs
  addons/clickhouse/configs/clickhouse-config-constraint.cue
  addons/clickhouse/templates/cmpd-ch.yaml
  addons/clickhouse/templates/config-template.yaml
  addons/clickhouse/templates/paramsdef.yaml
  addons/clickhouse/templates/pcr-keeper.yaml
  addons/clickhouse/templates/pcr.yaml
  addons/elasticsearch/templates/config-template.yaml
  addons/elasticsearch/templates/pcr-7.yaml
  addons/elasticsearch/templates/pcr-8.yaml
  addons/elasticsearch/templates/script-template.yaml
  addons/kafka/configs/2.7/kafka-27-server-constraint.cue
  addons/kafka/configs/kafka-server-constraint.cue
  addons/kafka/templates/config-template.yaml
  addons/kafka/templates/paramsdef.yaml
  addons/kafka/templates/paramsdef2.yaml
  addons/kafka/templates/pcr-broker.yaml
  addons/kafka/templates/pcr-broker2.yaml
  addons/kafka/templates/pcr-combine.yaml
  addons/kafka/templates/pcr-controller.yaml
  addons/kafka/templates/script-template.yaml
  addons/loki/templates/config-template.yaml
  addons/mogdb/config/mogdb-config-constraint.cue
  addons/mogdb/config/mogdb-config-effect-scope.yaml
  addons/mogdb/config/restart-parameter.yaml
  addons/mogdb/templates/config-template.yaml
  addons/mogdb/templates/paramsdef.yaml
  addons/mogdb/templates/pcr.yaml
  addons/mogdb/templates/script-template.yaml
  addons/mongodb/config/mongodb-config-constraint.cue
  addons/mongodb/templates/config-template.yaml
  addons/mongodb/templates/pcr.yaml
  addons/mongodb/templates/script-template.yaml
  addons/qdrant/templates/config-template.yaml
  addons/qdrant/templates/pcr.yaml
  addons/qdrant/templates/script-template.yaml
  addons/rabbitmq/config/config-constraint.cue
  addons/rabbitmq/config/config-effect-scope.yaml
  addons/rabbitmq/templates/config-template.yaml
  addons/rabbitmq/templates/paramsdef.yaml
  addons/rabbitmq/templates/pcr.yaml
  addons/weaviate/config/weaviate-env-constraint.cue
  addons/weaviate/templates/config-template.yaml
  addons/weaviate/templates/paramsdef.yaml
  addons/weaviate/templates/pcr.yaml
  addons/zookeeper/config/config-effect-scope.yaml
  addons/zookeeper/templates/pcr.yaml
Labels: pick-1.0-beta

#1603 chore: refine redis host network vars
  addons/redis/redis-cluster-scripts/redis-cluster-manage.sh
  addons/redis/redis-cluster-scripts/redis-cluster-server-start.sh
  addons/redis/scripts/redis-register-to-sentinel.sh
  addons/redis/scripts/redis-sentinel-start-v2.sh
  addons/redis/scripts/redis-start.sh
  addons/redis/templates/componentdefinition-redis-cluster.yaml
  addons/redis/templates/componentdefinition-redis-sentinel.yaml
  addons/redis/templates/componentdefinition-redis.yaml
Labels: nopick

#1614 chore: udpate invalid apecloud-mysql example
  addons/apecloud-postgresql/README.md
  addons/llm/README.md
  addons/loki/README.md
  addons/neon/README.md
  addons/orioledb/README.md
  addons/tdengine/README.md
  addons/victoria-metrics/README.md
  examples/apecloud-mysql/cluster-with-scheduling.yaml
  examples/apecloud-postgresql/README.md
  examples/llm/README.md
  examples/loki/README.md
  examples/neon/README.md
  examples/orioledb/README.md
  examples/tdengine/README.md
  examples/victoria-metrics/README.md
Labels: pick-1.0-beta

#1493 feat: support account provision for tidb
  addons/tidb/scripts/tidb_accountprovision.sh
  addons/tidb/scripts/tidb_postprovision.sh
  addons/tidb/templates/cmpd-tidb.yaml
  addons/tidb/templates/cmpv.yaml
  addons/tidb/values.yaml
Labels: pick-1.0-beta

#1618 chore: update mysql proxy tpl
  addons/mysql/config/proxysql.tpl
  addons/mysql/scripts/configure-proxysql.sh
  addons/mysql/scripts/proxysql-entry.sh
  addons/mysql/templates/cmpd-proxysql.yaml
Labels: pick-1.0-beta

#1619 chore: update mysql bpt with cmpd mysql-orc
  addons/mysql/templates/backuppolicytemplate.yaml
Labels: pick-1.0-beta

#1617 feat: add environment variable configurations for vminsert, vmselect and vmstorage
  addons-cluster/victoria-metrics/templates/cluster.yaml
  addons-cluster/victoria-metrics/values.yaml
Labels: pick-0.9, pick-1.0-beta

#1620 bugfix: restart when vmstorage hscale
  addons-cluster/victoria-metrics/templates/cluster.yaml
  addons-cluster/victoria-metrics/values.yaml
  addons/victoria-metrics/configs/vminsert-config.tpl
  addons/victoria-metrics/configs/vmselect-config.tpl
  addons/victoria-metrics/templates/cmpd-vminsert.yaml
  addons/victoria-metrics/templates/cmpd-vmselect.yaml
  addons/victoria-metrics/templates/cmpd-vmstorage.yaml
  addons/victoria-metrics/templates/configmap.yaml
  addons/victoria-metrics/values.yaml
Labels: pick-0.9, pick-1.0-beta

#1621 chore: update ob reconfig script
  addons/oceanbase-ce/reloader/update-parameters.sh
  addons/oceanbase-ce/reloader/update-sysvars.sh
Labels: pick-1.0-beta

#1624 chore: set ob podManagementPolicy to Parallel
  addons/oceanbase-ce/templates/componentdefinition.yaml
Labels: pick-1.0-beta

#1628 chore: tidy up switchover
  addons/apecloud-mysql/templates/_helpers.tpl
  addons/apecloud-postgresql/templates/_helpers.tpl
  addons/mongodb/templates/cmpd.yaml
  addons/mysql/templates/_helpers.tpl
  addons/postgresql/scripts/switchover.sh
  addons/redis/redis-cluster-scripts/redis-cluster-switchover.sh
  addons/redis/scripts/redis-switchover.sh
  addons/tidb/scripts/pd_switchover.sh
Labels: pick-1.0-beta

#1629 chore: update pg switchover action
  addons/postgresql/README.md
  addons/postgresql/scripts/switchover.sh
  addons/postgresql/templates/cmpd-12.yaml
  addons/postgresql/templates/cmpd-14.yaml
  addons/postgresql/templates/cmpd-15.yaml
  addons/postgresql/templates/cmpd-16.yaml
  examples/postgresql/rebuild.yaml
  examples/postgresql/switchover-specified-instance.yaml
  examples/postgresql/switchover.yaml
Labels: pick-1.0-beta

#1632 chore: update pg switchover test
  addons/postgresql/scripts-ut-spec/switchover_spec.sh
Labels: pick-1.0-beta

#1631 chore: update switchover ops with ns
  addons/apecloud-mysql/README.md
  addons/etcd/README.md
  addons/mogdb/README.md
  addons/mongodb/README.md
  addons/mysql/README.md
  addons/vanilla-postgresql/README.md
  examples/apecloud-mysql/switchover-specified-instance.yaml
  examples/apecloud-mysql/switchover.yaml
  examples/etcd/switchover.yaml
  examples/mogdb/switchover.yaml
  examples/mongodb/switchover-specified-instance.yaml
  examples/mongodb/switchover.yaml
  examples/mysql/switchover-specified-instance.yaml
  examples/mysql/switchover.yaml
  examples/redis/switchover-specified-instance.yaml
  examples/redis/switchover.yaml
  examples/vanilla-postgresql/switchover-specified-instance.yaml
  examples/vanilla-postgresql/switchover.yaml
Labels: pick-1.0-beta

#1635 chore: fix create rw error container compute not found
  addons/risingwave/templates/cmpd-connector.yaml
Labels: pick-1.0-beta

#1626 chore: remove apecloud-pg addon
  .github/CODEOWNERS
  README.md
  addons-cluster/apecloud-postgresql/.helmignore
  addons-cluster/apecloud-postgresql/Chart.yaml
  addons-cluster/apecloud-postgresql/templates/NOTES.txt
  addons-cluster/apecloud-postgresql/templates/_helpers.tpl
  addons-cluster/apecloud-postgresql/templates/cluster.yaml
  addons-cluster/apecloud-postgresql/templates/validate.yaml
  addons-cluster/apecloud-postgresql/values.schema.json
  addons-cluster/apecloud-postgresql/values.yaml
  addons/apecloud-postgresql/.helmignore
  addons/apecloud-postgresql/Chart.yaml
  addons/apecloud-postgresql/README.md
  addons/apecloud-postgresql/config/pg14-config-constraint.cue
  addons/apecloud-postgresql/config/pg14-config-effect-scope.yaml
  addons/apecloud-postgresql/config/pg14-config.tpl
  addons/apecloud-postgresql/reloader/update-parameter.sh
  addons/apecloud-postgresql/scripts-ut-spec/update_parameter_spec.sh
  addons/apecloud-postgresql/scripts/setup.sh
  addons/apecloud-postgresql/templates/clusterdefinition.yaml
  addons/apecloud-postgresql/templates/cmpd-apepg.yaml
  addons/apecloud-postgresql/templates/cmpv.yaml
  addons/apecloud-postgresql/templates/configmap.yaml
  addons/apecloud-postgresql/templates/paramsdef-14.yaml
  addons/apecloud-postgresql/templates/pcr-14.yaml
  addons/apecloud-postgresql/templates/scripts.yaml
  addons/apecloud-postgresql/values.yaml
  examples/apecloud-postgresql/README.md
  examples/apecloud-postgresql/cluster.yaml
  examples/apecloud-postgresql/expose-disable.yaml
  examples/apecloud-postgresql/expose-enable.yaml
  examples/apecloud-postgresql/horizontalscale.yaml
  examples/apecloud-postgresql/restart.yaml
  examples/apecloud-postgresql/start.yaml
  examples/apecloud-postgresql/stop.yaml
  examples/apecloud-postgresql/switchover.yaml
  examples/apecloud-postgresql/verticalscale.yaml
  examples/apecloud-postgresql/volumeexpand.yaml
Labels: pick-1.0-beta

#1639 chore: maintain the minio replicas history through a CM managed by itself
  addons/minio/scripts-ut-spec/initialize_patch_configmap_spec.sh
  addons/minio/scripts/replicas-history-config.sh
  addons/minio/scripts/startup.sh
  addons/minio/templates/_helpers.tpl
  addons/minio/templates/cmpd.yaml
  addons/minio/templates/config-template.yaml
  addons/minio/templates/minio-config-template.yaml
  addons/minio/templates/script-template.yaml
Labels: pick-1.0-beta

#1638 chore: tidy up clickhouse
  addons-cluster/clickhouse/templates/_helpers.tpl
  addons-cluster/clickhouse/templates/cluster.yaml
  addons-cluster/clickhouse/values.yaml
  addons/clickhouse/configs/00_default_overrides.xml.tpl
  addons/clickhouse/configs/ch_keeper_00_default_overrides.xml.tpl
  addons/clickhouse/configs/clickhouse-config-constraint.cue
  addons/clickhouse/configs/clickhouse-user-constraint.cue
  addons/clickhouse/dataprotection/backup.sh
  addons/clickhouse/dataprotection/common.sh
  addons/clickhouse/dataprotection/incremental-backup.sh
  addons/clickhouse/dataprotection/incremental-restore.sh
  addons/clickhouse/dataprotection/restore.sh
  addons/clickhouse/scripts/bootstrap-keeper.sh
  addons/clickhouse/scripts/bootstrap-server.sh
  addons/clickhouse/scripts/keeper-role-probe.sh
  addons/clickhouse/scripts/keeper-switchover.sh
  addons/clickhouse/scripts/member-join.sh
  addons/clickhouse/scripts/post-for-rebuild.sh
  addons/clickhouse/templates/_helpers.tpl
  addons/clickhouse/templates/actionset-incremental.yaml
  addons/clickhouse/templates/actionset.yaml
  addons/clickhouse/templates/backuppolicytemplate.yaml
  addons/clickhouse/templates/cmpd-ch-keeper.yaml
  addons/clickhouse/templates/cmpd-ch.yaml
  addons/clickhouse/templates/opsdefinition.yaml
  addons/clickhouse/templates/paramsdef-config.yaml
  addons/clickhouse/templates/paramsdef-keeper.yaml
  addons/clickhouse/templates/paramsdef-user.yaml
  addons/clickhouse/templates/pcr-ck.yaml
  addons/clickhouse/templates/pcr-keeper.yaml
  addons/clickhouse/templates/scripts.yaml
  addons/clickhouse/values.yaml
  addons/minio/README.md
  examples/clickhouse/backup.yaml
  examples/clickhouse/backuprepo.yaml
  examples/minio/cluster.yaml
Labels: pick-1.0-beta

#1640 chore: revert minio config name
  addons/minio/scripts/replicas-history-config.sh
Labels: pick-1.0-beta

#1641 fix: redis cluster restart failed
  addons/redis/redis-cluster-scripts/redis-cluster-server-start.sh
  addons/redis/templates/cmpd-redis-7.yaml
  addons/redis/templates/cmpd-redis-cluster-7.yaml
  addons/redis/templates/cmpd-redis-sentinel-7.yaml
Labels: pick-1.0-beta

#1644 chore: replace minio waiting role to notready
  addons/minio/templates/cmpd.yaml
Labels: pick-1.0-beta

#1642 chore: clickhouse grafana
  addons/clickhouse/dashboards/clickhouse.json
Labels: pick-1.0-beta

#1643 chore: update clickhouse schema and refine cue fmt
  addons/clickhouse/configs/clickhouse-config-constraint.cue
  addons/clickhouse/configs/clickhouse-user-constraint.cue
  addons/clickhouse/templates/paramsdef-config.yaml
  addons/clickhouse/templates/paramsdef-user.yaml
Labels: pick-1.0-beta

#1646 fix: redis-cluster scale in failed
  addons/redis/redis-cluster-scripts/redis-cluster-replica-member-leave.sh
  addons/redis/templates/cmpd-redis-cluster-7.yaml
Labels: pick-1.0-beta

#1647 fix: redis cluster start crash
  addons/redis/redis-cluster-scripts/redis-cluster-server-start.sh
Labels: pick-1.0-beta

#1648 fix: redis cluster start failed
  addons/redis/templates/cmpd-redis-7.yaml
  addons/redis/templates/cmpd-redis-cluster-7.yaml
  addons/redis/templates/cmpd-redis-sentinel-7.yaml
  addons/redis/templates/cmpd-redis-twemproxy.yaml
Labels: pick-1.0-beta

#1650 chore: ck compatible 0.9
  addons/clickhouse/scripts/bootstrap-keeper.sh
  addons/clickhouse/scripts/bootstrap-server.sh
Labels: pick-1.0-beta

#1651 chore: compatible 0.9 clickhouse
  addons/clickhouse/scripts/bootstrap-keeper.sh
Labels: pick-1.0-beta

#1653 chore: add pgaudit.log in cue
  addons/orioledb/config/pg16-config-constraint.cue
  addons/postgresql/config/pg12-config-constraint.cue
  addons/postgresql/config/pg14-config-constraint.cue
  addons/postgresql/config/pg15-config-constraint.cue
  addons/postgresql/config/pg16-config-constraint.cue
Labels: pick-1.0-beta
